### ISSUE TITLE
Dries i need your help with this

### ISSUE THREAD

**Issue by TonyWAV** [WavUncraft/HGCore#1]
Dries check the syntax on line 43 at main.php thanks because its not working

**Comment by TonyWAV** [comment]
Please help me fix this dries

**Comment by Driesboy** [comment]
i am here

**Comment by TonyWAV** [comment]
check the line 43

**Comment by Driesboy** [comment]
where

**Comment by TonyWAV** [comment]
Its not working and server crash on start please check the problem

**Comment by Driesboy** [comment]
I cannot find that

**Comment by TonyWAV** [comment]
try to use this plugin dries to see the problem

**Comment by Driesboy** [comment]
Ok

**Comment by TonyWAV** [comment]
dries did you fix?

**Comment by Driesboy** [comment]
no i cannot find the line

**Comment by Driesboy** [comment]
tony???

**Comment by ankitmaharjan252** [comment]
I've fixed that errors. Try it now after merging my Pull Request
